# # Uninstall Nginx
# - name: Play - Uninstall Nginx
#   hosts: localhost
#   become: yes
#   tasks: 
#     - name: Unnstall Nginx
#       apt: name=nginx state=absent

- name: Play - Install and configure Nginx as a LoadBalancer
  hosts: localhost
  become: yes
  tasks:
    - name: Update cache
      apt: update_cache=yes   
      
    - name: Install Nginx
      apt:
        name: nginx
        state: present

    - name: Copy the Nginx config file to /etc/nginx/sites-available
      copy:
        src: ./nginx.cfg
        dest: /etc/nginx/sites-available/nginx.cfg
      become: yes

    - name: Create symlink of the config file at /etc/nginx/sites-enabled
      file:
        src: /etc/nginx/sites-available/nginx.cfg
        dest: /etc/nginx/sites-enabled/nginx.cfg
        state: link
      become: yes

    - name: Restart nginx to apply changes
      service:
        name: nginx
        state: restarted

